"""Modification des champs du modèle Resto

Revision ID: fca37fb9eac4
Revises: 44a947abfd71
Create Date: 2025-01-13 14:02:50.618961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fca37fb9eac4'
down_revision = '44a947abfd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_plat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('restaurant_name')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('photo')
        batch_op.drop_column('description_plat')

    # ### end Alembic commands ###
